- name: 'Install certbot'
  hosts: all
  become: true

  tasks:
    - name: Install certbot
      apt:
        pkg:
          - software-properties-common
          - python3-certbot-apache
        state: present
      tags: [ system, letsencrypt ]

    - name: Register domain
      shell: "/usr/bin/certbot --apache -d {{ domain_name }} --non-interactive --agree-tos --email {{ email }}"
      tags: [ letsencrypt ]

    - name: Renew dry run
      shell: "/usr/bin/certbot renew --dry-run"
      tags: [ letsencrypt ]